### ISSUE TITLE
写评论里的 “删除标记” 弹出窗口里的 “确认” 和 “取消” 键，字体颜色与背景色一样

### ISSUE THREAD

**Issue by Duuck-D** [Number178/kikoeru-quasar#2]
写评论里的 “删除标记” 弹出窗口里的 “确认” 和 “取消” 键，字体颜色与背景色一样，无法分辨

![Snipaste_2024-06-04_17-45-53](https://github.com/Number178/kikoeru-quasar/assets/30623152/dcdd5d7d-ace6-4a5f-ae87-74646cdf3d71)

**Comment by Number178** [comment]
已修复，可拉取最新版本再试试

**Comment by Duuck-D** [comment]
好的，已解决，谢谢
